services:
  - type: web
    name: bus-booking-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn travels.wsgi:application
